### ISSUE TITLE
Ambiguous occurrence 'length'

### ISSUE THREAD

**Issue by Gooberpatrol66** [wavewave/xournal-types#1]
Configuring xournal-types-0.5.1...
Building xournal-types-0.5.1...
Preprocessing library xournal-types-0.5.1...
[1 of 8] Compiling Data.Xournal.Predefined ( src/Data/Xournal/Predefined.hs, dist/build/Data/Xournal/Predefined.o )
[2 of 8] Compiling Data.Xournal.Util ( src/Data/Xournal/Util.hs, dist/build/Data/Xournal/Util.o )
[3 of 8] Compiling Data.Xournal.Simple ( src/Data/Xournal/Simple.hs, dist/build/Data/Xournal/Simple.o )
[4 of 8] Compiling Data.Xournal.Generic ( src/Data/Xournal/Generic.hs, dist/build/Data/Xournal/Generic.o )
[5 of 8] Compiling Data.Xournal.BBox ( src/Data/Xournal/BBox.hs, dist/build/Data/Xournal/BBox.o )
[6 of 8] Compiling Data.Xournal.Map ( src/Data/Xournal/Map.hs, dist/build/Data/Xournal/Map.o )
[7 of 8] Compiling Data.Xournal.Select ( src/Data/Xournal/Select.hs, dist/build/Data/Xournal/Select.o )

src/Data/Xournal/Select.hs:55:33:
    Ambiguous occurrence ‘length’
    It could refer to either ‘Data.Foldable.length’,
                             imported from ‘Data.Foldable’ at src/Data/Xournal/Select.hs:23:1-20
                          or ‘Data.Sequence.length’,
                             imported from ‘Data.Sequence’ at src/Data/Xournal/Select.hs:25:1-20

src/Data/Xournal/Select.hs:55:46:
    Ambiguous occurrence ‘length’
    It could refer to either ‘Data.Foldable.length’,
                             imported from ‘Data.Foldable’ at src/Data/Xournal/Select.hs:23:1-20
                          or ‘Data.Sequence.length’,
                             imported from ‘Data.Sequence’ at src/Data/Xournal/Select.hs:25:1-20

src/Data/Xournal/Select.hs:59:35:
    Ambiguous occurrence ‘length’
    It could refer to either ‘Data.Foldable.length’,
                             imported from ‘Data.Foldable’ at src/Data/Xournal/Select.hs:23:1-20
                          or ‘Data.Sequence.length’,
                             imported from ‘Data.Sequence’ at src/Data/Xournal/Select.hs:25:1-20

src/Data/Xournal/Select.hs:91:15:
    Ambiguous occurrence ‘length’
    It could refer to either ‘Data.Foldable.length’,
                             imported from ‘Data.Foldable’ at src/Data/Xournal/Select.hs:23:1-20
                          or ‘Data.Sequence.length’,
                             imported from ‘Data.Sequence’ at src/Data/Xournal/Select.hs:25:1-20

src/Data/Xournal/Select.hs:92:15:
    Ambiguous occurrence ‘length’
    It could refer to either ‘Data.Foldable.length’,
                             imported from ‘Data.Foldable’ at src/Data/Xournal/Select.hs:23:1-20
                          or ‘Data.Sequence.length’,
                             imported from ‘Data.Sequence’ at src/Data/Xournal/Select.hs:25:1-20

**Comment by wavewave** [comment]
Thanks for the report. I will fix it. BTW, this repo is now deprecated by being incorporated into wavewave/hoodle mega-repository. Please report any issues there afterwards. Thanks!

**Comment by wavewave** [comment]
Okay. this issue was handled by this commit, but I haven't updated the hackage yet.
https://github.com/wavewave/hoodle/commit/37a132e3c1836bb8fcfb0b2d1cff15d87ff13135

Please try the latest version from xournal-types from hoodle main repo. I will upload the new version soon.
